# RuboCop configuration for cyber-trackr-live gem
# API client gem with generated code and custom helpers

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1
  Exclude:
    - 'site/**/*'
    - 'lib/cyber_trackr_client.rb'    # Generated entry point file
    - 'lib/cyber_trackr_client/**/*'  # Generated client code
    - 'docs/**/*'
    - 'vendor/**/*'
    - '.bundle/**/*'
    - 'test/fixtures/**/*'
    - 'scripts/debug/**/*'
    - 'examples/**/*'
    - 'analyze*.rb'
    - 'quick_*.rb'
    - 'fetch_*.rb'
    - '*.json'
    - '*.txt'
    - '*.md'

# Exclude generated client code from certain rules
Style/SafeNavigation:
  Exclude:
    - 'lib/cyber_trackr_client/**/*'  # Generated code

# Network plugins need longer classes for connection handling
Metrics/ClassLength:
  Max: 310  # Connection classes handle SSH, auth, commands, etc.

# Network initialization involves many configuration options
Metrics/MethodLength:
  Max: 60  # SSH setup, proxy config, session initialization

Metrics/AbcSize:
  Max: 60  # Complex network setup methods

Metrics/CyclomaticComplexity:
  Max: 25  # Network auth and proxy logic (initialize: 20, connect: 18)

Metrics/PerceivedComplexity:
  Max: 25  # Error handling for network scenarios

Metrics/ModuleLength:
  Max: 120  # Platform detection modules need more space

# Test files have naturally long describe blocks
Metrics/BlockLength:
  Max: 50  # Allow longer blocks for gemspec and test files
  AllowedMethods:
    - describe
    - context
    - it
  Exclude:
    - '**/*_test.rb'
    - 'test/**/*'
    - 'spec/**/*'
    - '*.gemspec'

# Line length - allow longer lines for network config and gem descriptions
Layout/LineLength:
  Max: 175  # Gem descriptions, error messages, and API docs can be long

# Allow constants in test blocks (MockResult class)
Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'test/**/*'

# Follow RubyGems standards for gemspec development dependencies
Gemspec/DevelopmentDependencies:
  Enabled: false

# File naming - train-juniper.rb is the standard entry point name
Naming/FileName:
  Exclude:
    - 'lib/train-juniper.rb'

# String literals - relax for network plugins
Style/StringLiterals:
  EnforcedStyle: single_quotes

# Guard clause - can be problematic with complex error handling
Style/GuardClause:
  Enabled: false  # Network plugins have complex nested error handling

# Identical conditional branches - can break heredoc error messages
Style/IdenticalConditionalBranches:
  Enabled: false  # Network plugins return similar results for different paths

# Allow compact module definition for plugins  
Style/ClassAndModuleChildren:
  Enabled: false  # Train plugins use compact TrainPlugins::PluginName format

# Allow STDOUT for logger output in network plugins
Style/GlobalStdStream:
  Exclude:
    - 'lib/train-juniper/connection.rb'  # Logger defaults to STDOUT
    - 'test/**/*'  # Test files may use STDOUT

# Platform detection has expected duplicate architecture mappings
Lint/DuplicateBranch:
  Exclude:
    - 'lib/train-juniper/platform.rb'  # Platform arch detection has expected duplicates
  
# Documentation requirements
Style/Documentation:
  Enabled: false  # Network plugins have different doc patterns

# Predicate naming - allow is_* for domain-specific predicates
Naming/PredicatePrefix:
  Exclude:
    - 'lib/cyber_trackr_helper.rb'  # is_srg? is domain-specific and clear

# Variable naming - allow V_123456 style for STIG vulnerability IDs
Naming/VariableNumber:
  Exclude:
    - 'test/**/*'  # Test files use STIG V-IDs and response_200 style names

# Block nesting - test files may have deeper nesting for complex validation
Metrics/BlockNesting:
  Exclude:
    - 'test/**/*'  # Test validation logic may need deeper nesting